---
title: "Compare_residual_margins"
output: html_document
date: "2024-09-24"
---

```{r setup, include=FALSE}
library(tidyverse)
library(latex2exp)
knitr::opts_chunk$set(echo = TRUE)
# set theme defaults to be black rectangle
theme_set(theme_bw())
theme_replace(
  panel.spacing = unit(2, "lines"),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  strip.background = element_blank(),
  panel.border = element_rect(colour = "black", fill = NA) )
file.sources = list.files(pattern="*helpers.R")
sapply(file.sources,source,.GlobalEnv)
```

## Simulate data

Simulate from trivariate Markov chain with logistic copula links and Laplace margins.

```{r }
set.seed(11)
N <- 500
v <- 0.99 # threshold for conditioning variable
sims <- generate_Y(N=N) %>% link_log(dep=1/2) %>%
  link_log(dep=1/2) %>% link_log(dep=1/2) %>% link_log(dep=1/2) %>%
  apply(c(1,2),FUN=frechet_laplace_pit) %>% as.data.frame()
```

## Motivate the problem

Simulate a large sample from a logistic distribution.

```{r}
set.seed(11)
N <- 50000
v <- 0.99 # threshold for conditioning variable
sims <- generate_Y(N=N) %>% link_log(dep=1/2) %>%
  link_log(dep=1/2) %>% link_log(dep=1/2) %>% link_log(dep=1/2) %>%
  apply(c(1,2),FUN=frechet_laplace_pit) %>% as.data.frame()
obsr <- observed_residuals(df=sims,given=1,v=v)
df <- data.frame(y=g_laplace(z=seq(-7.5,5,0.01),a=1/2),x=seq(-7.5,5,0.01))
ggplot(obsr) + geom_density(mapping = aes(x=Z2)) + geom_line(data=df,mapping = aes(x=x,y=y),col="#C11432") + xlab(TeX("$Z_2$")) + ylab("Residual density function")
```

## Calculate MLE for different methods

```{r}
L1 <- par_est(df=sims,v=v,given=c(1:5),margin = "AGG", method = "two_step")
L2 <- par_est(df=sims,v=v,given=c(1:5),margin = "AGGsig", method = "two_step")
L3 <- par_est(df=sims,v=v,given=c(1:5),margin = "AGGsigdelta", method = "two_step")
# L3 <- par_est(df=sims,v=v,given=1,margin = "AGG", method = "two_step")$lik2
#par_est(df=sims,v=v,given=1,margin = "AGGsig", method = "two_step")$lik2

sum(2*((L2$lik2)-(L1$lik2))>pchisq(0.95,1))/nrow(L1)
sum(2*((L3$lik2)-(L2$lik2))>pchisq(0.99,1))/nrow(L1)
sum(2*((L3$lik2)-(L1$lik2))>pchisq(0.99,1))/nrow(L1)
2*((L2$lik2)-(L1$lik2))
2*((L3$lik2)-(L2$lik2))
2*((L3$lik2)-(L1$lik2))

```

Specifically compare considering different scale or shape parameter or both.
```{r}
N <- 50000
v <- 0.99
M <- 100
L1 <- list()
L2 <- list()
L3 <- list()
for (i in 1:M) {
  # simulate a sample
  set.seed(12*i)
  sims <- generate_Y(N=N) %>% link_log(dep=1/2) %>%
    link_log(dep=1/2) %>% link_log(dep=1/2) %>% link_log(dep=1/2) %>%
    apply(c(1,2),FUN=frechet_laplace_pit) %>% as.data.frame()
# calculate log-likelihoods cond on 1 and save in a list
L1[[i]] <- par_est(df=sims,v=v,given=c(1),margin = "AGG", method = "two_step")$lik2
L2[[i]] <- par_est(df=sims,v=v,given=c(1),margin = "AGGsig", method = "two_step")$lik2
L3[[i]] <- par_est(df=sims,v=v,given=c(1),margin = "AGGsigdelta", method = "two_step")$lik2
}

# plot boxplots for a,b,mu,sig estimated values
AGGdelta <- c()
AGGsig <- c()
AGGsigdelta <- c()
res <- rep(c("Z2","Z3","Z4","Z5"),length(L1))
for (i in 1:length(L1)) {
  AGGdelta <- append(AGGdelta,as.numeric(unlist(L1[[i]])))
  AGGsig <- append(AGGsig,as.numeric(unlist(L2[[i]])))
  AGGsigdelta <- append(AGGsigdelta,as.numeric(unlist(L3[[i]])))
}

p1 <- ggplot(data.frame(x=factor(res,levels=c("Z2","Z3","Z4","Z5")),y=AGGsigdelta),aes(x=x,y=y))+
  geom_boxplot() + xlab("Observed residuals") + ylab(TeX("$l(\\mu,\\sigma_l,\\sigma_u,\\delta_l,\\delta_u)$"))
p2 <- ggplot(data.frame(x=factor(res,levels=c("Z2","Z3","Z4","Z5")),y=AGGdelta),aes(x=x,y=y))+
  geom_boxplot() + xlab("Observed residuals") + ylab(TeX("$l(\\mu,\\sigma,\\delta_l,\\delta_u)$"))
p3 <- ggplot(data.frame(x=factor(res,levels=c("Z2","Z3","Z4","Z5")),y=AGGsig),aes(x=x,y=y))+
  geom_boxplot() + xlab("Observed residuals") + ylab(TeX("$l(\\mu,\\sigma_l,\\sigma_u,\\delta)$"))
grid.arrange(p1,p2,p3,ncol=3)

```

