---
title: "Vine structure comparison"
output: html_document
date: "2025-03-18"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(VineCopula)
library(rvinecopulib)
library(tidyverse)
library(texmex)
```

```{r}
v <- 0.7
# transform to Laplace margins
winter_lap <- as.data.frame((winter %>% apply(c(2),FUN=row_number))/(nrow(winter)+1)) %>% apply(c(1,2),FUN=unif_laplace_pit) %>% as.data.frame()
summer_lap <- as.data.frame((summer %>% apply(c(2),FUN=row_number))/(nrow(summer)+1)) %>% apply(c(1,2),FUN=unif_laplace_pit) %>% as.data.frame()
pew <-  par_est(df=winter_lap,v=v,given=j,margin = "AGG", method = "sequential2")
obsresw <- (observed_residuals(df = winter_lap,given = 1,v = v,a = pew$a,b=pew$b) %>% apply(c(2),FUN=row_number))/(nrow(winter_lap)*(1-v)+1)

pes <-  par_est(df=summer_lap,v=v,given=j,margin = "AGG", method = "sequential2")
obsress <- (observed_residuals(df = summer_lap,given = 1,v = v,a = pes$a,b=pes$b) %>% apply(c(2),FUN=row_number))/(nrow(summer_lap)*(1-v)+1)

vcw1 <- rvinecopulib::vinecop(data=obsresw)
vcw1
summary(vc1)
# compare with VineCopula fit
vcw2 <- VineCopula::RVineStructureSelect(data=obsresw)
summary(vcw2)

vcs1 <- rvinecopulib::vinecop(data=obsress)
vcs1
summary(vcs1)
# compare with VineCopula fit
vcs2 <- VineCopula::RVineStructureSelect(data=obsress)
summary(vcs2)
```


## Impose tree structure and copula families


## Compare imposing one link at a time

Try the residuals of $NO_2$ and $NO$.

```{r}
summary(vc2)

bivc <- VineCopula::RVineStructureSelect(data=obsresw[,1:2])
RVineSeqEst(data=obsress[,1:2],RVM=bivc)

# look at other way around
bivc <- VineCopula::RVineStructureSelect(data=obsress[,1:2])
RVineSeqEst(data=obsresw[,1:2],RVM=bivc)


```

Try another pair of $SO_2$ and $PM_{10}$ residuals.

```{r}
summary(vc2)

bivc <- VineCopula::RVineStructureSelect(data=obsresw[,3:4])
RVineSeqEst(data=obsress[,3:4],RVM=bivc)

# look at other way around
bivc <- VineCopula::RVineStructureSelect(data=obsress[,3:4])
RVineSeqEst(data=obsresw[,3:4],RVM=bivc)

```

## Try all possible bivariate coplas for a given link

```{r}
index_cop <- c(0:10,13,16,18,20,23,24,26:30,33,34,36:40,104,114,124,134,204,214,224)
x <- list()
tmp <- obsresw[,1:2]
tmp1 <- obsress[,1:2]

for (i in 1:length(index_cop)) {
  tryCatch({
x[[i]] <-  BiCopEst(u1=as.numeric(tmp[,1]),u2=as.numeric(tmp[,2]),family=i)$AIC
  },error=function(e){print(NA)})
}
```

Try the Shiny app for comparing copula fits.

```{r}
BiCopCompare(u1=obsresw[,1],u2=obsresw[,2])

# Try another pair of SO2 and PM10
BiCopCompare(u1=obsresw[,3],u2=obsresw[,4])


BiCopCompare(u1=obsresw[,2],u2=obsresw[,3])
```

